### ISSUE TITLE
Config generation

### ISSUE THREAD

**Issue by examinedliving** [muzzley/mobile-icon-resizer#11]
I worked out a quick and dirty script to do this for my own purposes, but it might be useful to have something that allows one to output the lines of code that are required for the `config.xml` file.   This could either be outputted to a _partial_ `.xml` file or directly outputted to the actual `config.xml` file.  

As I said, in my case, it was quick and dirty - I was using only `IOS` and I knew exactly how I wanted my XML formatted, but given the number of possible ways that this can be done with Cordova/XCode/etc., you may say this is more trouble than it's worth.

If it was limited (like opinionated)  in some way, it might be easier to implement.  Anyway; I'd be happy to do some work on this if you think it would be worth pursuing - or if there is some structure you can see that would allow for limiting the vast array of formatting options.

**Comment by tiagoalves** [comment]
I'm very reluctant to accept such a feature because I'm not a mobile dev guy and would not even know how to maintain it. Also, as you said, there are many different ways to output the config information.

This tool can be required by any other project as explained in the README [here](https://github.com/muzzley/mobile-icon-resizer#module).

What do you think of creating a stand-alone tool that uses this tool? We could modify this tool to export and/or calculate stuff you'd need for your own tool in a generic way and you'd output it in whatever format you need. Does this make sense?

**Comment by examinedliving** [comment]
It does make sense, and sounds like a good idea.  I'm interested in possibly pursuing this further.
